---
deployment:
      tasks:
        - export DEPLOYPATH=/home/rindujanda/repositories/wandi  # Add /<app_folder> if required
        - /bin/cp * $DEPLOYPATH                 #Copy specific file to destination from root
        - /bin/cp /*/* $DEPLOYPATH   #copy specific file from source sub folder
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin cp /*/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH  
